dist: bionic # this is the most recent Ubuntu image available
language: cpp
cache: ccache
matrix:
  include:
    # GCC 10 on Linux
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-10
      env:
        - MATRIX_EVAL="CXX=g++-10"
    # Clang 10 on Linux
    - os: linux
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-10 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - clang-10
      env:
        - MATRIX_EVAL="CXX=clang++-10"
    # Clang 10 on macOS
    - os: osx
    # xcode10.3 image has CLang 10.0.1 (same as Linux) and CMake 3.15, however
    # we're using a newer image because the C++ standard library doesn't support
    # our need for constexpr-safe std::array usage
      osx_image: xcode11.4
      env:
        - MATRIX_EVAL="CXX=clang++"
before_install:
  - eval "${MATRIX_EVAL}"
before_script:
  - cd build
  - cmake ..
script:
  - make -j -k
  - ./unit_tests
