dist: bionic # this is the most recent Ubuntu image available
language: cpp
cache: ccache
matrix:
  include:
    # GCC 10 on Linux
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-10
      env:
        - MATRIX_EVAL="CXX=g++-10"
    # Clang 10 on Linux
    - os: linux
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-bionic-10
          packages:
            - clang-10
      env:
        - MATRIX_EVAL="CC=clang-10 && CXX=clang++-10"
before_install:
  - if [ "$CXX" == "clang++-10" ]; then sudo apt-get -y install clang-10; fi
  - eval "${MATRIX_EVAL}"
before_script:
  - cd build
  - cmake ..
script:
  - make -j -k
  - ./unit_tests
